default_platform(:ios)

platform :ios do
  desc "Upload the release IPA (already built by CI) to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true,
      in_house: false
    )

    ipa_path = Dir.glob("../**/*.ipa").first
    UI.user_error!("No .ipa file found next to the ios/ directory") unless ipa_path

    upload_to_testflight(
      api_key: api_key,
      ipa: ipa_path,
      skip_waiting_for_build_processing: true
    )
  end
end
